version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "checkSQS"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1cu9dag0s2ywr"
s3_prefix = "checkSQS"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
